const express = require("express");
const router = express.Router();
const bookController = require("../controllers/bookController");
const checkAuth = require("../middleware/authMiddleware");
router.get("/", bookController.getAllBooks);
router.get("/:id", bookController.getBookById);
router.post("/", checkAuth, bookController.createBook);
router.put("/:id", checkAuth, bookController.updateBook);
router.delete("/:id", checkAuth, bookController.deleteBook);
module.exports = router;
